### PR TITLE
Fix this thing

### PR DESCRIPTION
**Pull request by noerw**

### CODE REVIEW

**Comment by noerw** [comment]
anything else requiring changes? these fixes were suprisingly easy, so i have room for more :^)

**Comment by christophfriedrich** [comment]
Regarding review: Can you deploy it somewhere so we can test it live?

Further tasks:
1. Table rendering in the preview used to be broken
2. Fill in the date in the header automatically with the current time
3. Ask user for the room on startup (two buttons "147", "255" and an input for other)
4. Tasks always need to be copied to the wiki and the email by the Protokollant - having a button to export them in the respective format would be handy
5. Like 4., auto-generating a message to sent to the mailinglist (or even sending it from the FS account?) would be handy

In general, what I'm dreaming of is a one-stop all-in-one Sitzungsmanagement tool, including invitations, attendance notices, (connected to that) automatic Kuchenstrich allocation, Protokollant tracking (that also suggests whose turn it is)...

**Comment by noerw** [comment]
changes are minimal and can be inferred from the commit messages, but  i guess i will deploy it in production env tonight, there's enough time till next session to revert it if needed.

kuchenstrich allocation, gotta keep this one :'D

**Comment by noerw** [comment]
it's deployed, see geofs.de/protokolle

**Comment by christophfriedrich** [comment]
> lets keep this PR to "fix long standing issues so everybody is happy enough for now"

100% d'accord, I just let loose my imagination because you asked for more work :D I also think that a full rewrite (or development of a completely different tool in which Protokolle are just one subcomponent) would be necessary for that.

I just realised that I indeed filed my no. 1 from above as #5 a while ago. So maybe you could include my no. 2 into this PR (seems fairly simple to me and updating the date is often forgotten by the Protokollant), and leave the rest for later(TM).

**Comment by christophfriedrich** [comment]
I filed my no. 2 as #9 and thought of another little thing (#10).

Meanwhile I had a look at the deployed version - it looks a lot cleaner now, so definitely an improvement and therefore no objections from my side to merge this into master.

**Comment by SpeckiJ** [comment]
@christophfriedrich https is handled by the apache2 proxy server and not by the tool itself. Therefore https integration is superflous here.

**Pull request merged**
